GET http://localhost:3002/api/users


### Get one user
GET http://localhost:3002/api/users/2

### Create new user
POST http://localhost:3002/api/users
Content-Type: application/json

{
    "username" : "Gordon",
    "email" : "gordon@example.com",
    "password" : "pass123"
}

### Update new user
PUT http://localhost:3002/api/users/1
Content-Type: application/json

{
    "username" : "Ton",
    "email" : "ton@example.com",
    "password" : "pass123"
}

### Delete User
DELETE http://localhost:3002/api/users/5